// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackpath/vk-stackpath-provider/internal/api/workload/workload_client/workloads (interfaces: ClientService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	runtime "github.com/go-openapi/runtime"
	gomock "github.com/golang/mock/gomock"
	workloads "github.com/stackpath/vk-stackpath-provider/internal/api/workload/workload_client/workloads"
)

// WorkloadsClientService is a mock of ClientService interface.
type WorkloadsClientService struct {
	ctrl     *gomock.Controller
	recorder *WorkloadsClientServiceMockRecorder
}

// WorkloadsClientServiceMockRecorder is the mock recorder for WorkloadsClientService.
type WorkloadsClientServiceMockRecorder struct {
	mock *WorkloadsClientService
}

// NewWorkloadsClientService creates a new mock instance.
func NewWorkloadsClientService(ctrl *gomock.Controller) *WorkloadsClientService {
	mock := &WorkloadsClientService{ctrl: ctrl}
	mock.recorder = &WorkloadsClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *WorkloadsClientService) EXPECT() *WorkloadsClientServiceMockRecorder {
	return m.recorder
}

// CreateWorkload mocks base method.
func (m *WorkloadsClientService) CreateWorkload(arg0 *workloads.CreateWorkloadParams, arg1 runtime.ClientAuthInfoWriter, arg2 ...workloads.ClientOption) (*workloads.CreateWorkloadOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWorkload", varargs...)
	ret0, _ := ret[0].(*workloads.CreateWorkloadOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkload indicates an expected call of CreateWorkload.
func (mr *WorkloadsClientServiceMockRecorder) CreateWorkload(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkload", reflect.TypeOf((*WorkloadsClientService)(nil).CreateWorkload), varargs...)
}

// DeleteWorkload mocks base method.
func (m *WorkloadsClientService) DeleteWorkload(arg0 *workloads.DeleteWorkloadParams, arg1 runtime.ClientAuthInfoWriter, arg2 ...workloads.ClientOption) (*workloads.DeleteWorkloadNoContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteWorkload", varargs...)
	ret0, _ := ret[0].(*workloads.DeleteWorkloadNoContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkload indicates an expected call of DeleteWorkload.
func (mr *WorkloadsClientServiceMockRecorder) DeleteWorkload(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkload", reflect.TypeOf((*WorkloadsClientService)(nil).DeleteWorkload), varargs...)
}

// GetLocations mocks base method.
func (m *WorkloadsClientService) GetLocations(arg0 *workloads.GetLocationsParams, arg1 runtime.ClientAuthInfoWriter, arg2 ...workloads.ClientOption) (*workloads.GetLocationsOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLocations", varargs...)
	ret0, _ := ret[0].(*workloads.GetLocationsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocations indicates an expected call of GetLocations.
func (mr *WorkloadsClientServiceMockRecorder) GetLocations(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocations", reflect.TypeOf((*WorkloadsClientService)(nil).GetLocations), varargs...)
}

// GetWorkload mocks base method.
func (m *WorkloadsClientService) GetWorkload(arg0 *workloads.GetWorkloadParams, arg1 runtime.ClientAuthInfoWriter, arg2 ...workloads.ClientOption) (*workloads.GetWorkloadOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWorkload", varargs...)
	ret0, _ := ret[0].(*workloads.GetWorkloadOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkload indicates an expected call of GetWorkload.
func (mr *WorkloadsClientServiceMockRecorder) GetWorkload(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkload", reflect.TypeOf((*WorkloadsClientService)(nil).GetWorkload), varargs...)
}

// GetWorkloads mocks base method.
func (m *WorkloadsClientService) GetWorkloads(arg0 *workloads.GetWorkloadsParams, arg1 runtime.ClientAuthInfoWriter, arg2 ...workloads.ClientOption) (*workloads.GetWorkloadsOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWorkloads", varargs...)
	ret0, _ := ret[0].(*workloads.GetWorkloadsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloads indicates an expected call of GetWorkloads.
func (mr *WorkloadsClientServiceMockRecorder) GetWorkloads(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloads", reflect.TypeOf((*WorkloadsClientService)(nil).GetWorkloads), varargs...)
}

// SetTransport mocks base method.
func (m *WorkloadsClientService) SetTransport(arg0 runtime.ClientTransport) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTransport", arg0)
}

// SetTransport indicates an expected call of SetTransport.
func (mr *WorkloadsClientServiceMockRecorder) SetTransport(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTransport", reflect.TypeOf((*WorkloadsClientService)(nil).SetTransport), arg0)
}

// UpdateWorkload mocks base method.
func (m *WorkloadsClientService) UpdateWorkload(arg0 *workloads.UpdateWorkloadParams, arg1 runtime.ClientAuthInfoWriter, arg2 ...workloads.ClientOption) (*workloads.UpdateWorkloadOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateWorkload", varargs...)
	ret0, _ := ret[0].(*workloads.UpdateWorkloadOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkload indicates an expected call of UpdateWorkload.
func (mr *WorkloadsClientServiceMockRecorder) UpdateWorkload(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkload", reflect.TypeOf((*WorkloadsClientService)(nil).UpdateWorkload), varargs...)
}
