resources:
  - namespace.yaml
  - vk-deployment.yaml
  - cluster-role.yaml
  - service-account.yaml

namespace: default

secretGenerator:
  - name: sp-vk-secrets
    env: config.properties

configMapGenerator:
  - name: sp-vk-location
    literals:
      - SP_CITY_CODE=DFW
  - name: cert-gen
    files:
      - "scripts/cert-gen.sh"
      - "scripts/csr.conf"

images:
  - name: ghcr.io/stackpath/virtual-kubelet-stackpath
    newTag: latest
