apiVersion: v1
kind: Pod
metadata:
  name: vk-sp
spec:
  containers:
    - name: vk-sp
      image: ghcr.io/stackpath/virtual-kubelet-stackpath:v0.3.0
      command:
        - virtual-kubelet
      ports:
        - containerPort: 10250
      envFrom:
        - secretRef:
            name: sp-vk-secrets
        - configMapRef:
            name: sp-vk-location
      env:
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APISERVER_CERT_LOCATION
          value: /etc/virtual-kubelet/cert.pem
        - name: APISERVER_KEY_LOCATION
          value: /etc/virtual-kubelet/key.pem
      volumeMounts:
        - name: certs-volume
          mountPath: /etc/virtual-kubelet
  initContainers:
    - name: cert-generator
      image: ubuntu:latest
      command: ["sh", "-c"]
      args:
        - |
          /usr/bin/bash /tmp/cert/cert-gen.sh
      volumeMounts:
        - name: certs-volume
          mountPath: /etc/virtual-kubelet
        - name: cert-gen
          mountPath: /tmp/cert
  volumes:
    - name: certs-volume
      emptyDir: {}
    - name: cert-gen
      configMap:
        name: cert-gen
  serviceAccountName: virtual-kubelet-sp
