// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stackpath/virtual-kubelet-stackpath/internal/api/workload/workload_models"
)

// DeleteImagesForFamilyReader is a Reader for the DeleteImagesForFamily structure.
type DeleteImagesForFamilyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteImagesForFamilyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteImagesForFamilyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteImagesForFamilyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteImagesForFamilyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteImagesForFamilyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteImagesForFamilyNoContent creates a DeleteImagesForFamilyNoContent with default headers values
func NewDeleteImagesForFamilyNoContent() *DeleteImagesForFamilyNoContent {
	return &DeleteImagesForFamilyNoContent{}
}

/*
DeleteImagesForFamilyNoContent describes a response with status code 204, with default header values.

No content
*/
type DeleteImagesForFamilyNoContent struct {
}

// IsSuccess returns true when this delete images for family no content response has a 2xx status code
func (o *DeleteImagesForFamilyNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete images for family no content response has a 3xx status code
func (o *DeleteImagesForFamilyNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete images for family no content response has a 4xx status code
func (o *DeleteImagesForFamilyNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete images for family no content response has a 5xx status code
func (o *DeleteImagesForFamilyNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete images for family no content response a status code equal to that given
func (o *DeleteImagesForFamilyNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete images for family no content response
func (o *DeleteImagesForFamilyNoContent) Code() int {
	return 204
}

func (o *DeleteImagesForFamilyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyNoContent ", 204)
}

func (o *DeleteImagesForFamilyNoContent) String() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyNoContent ", 204)
}

func (o *DeleteImagesForFamilyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImagesForFamilyUnauthorized creates a DeleteImagesForFamilyUnauthorized with default headers values
func NewDeleteImagesForFamilyUnauthorized() *DeleteImagesForFamilyUnauthorized {
	return &DeleteImagesForFamilyUnauthorized{}
}

/*
DeleteImagesForFamilyUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type DeleteImagesForFamilyUnauthorized struct {
	Payload *workload_models.StackpathapiStatus
}

// IsSuccess returns true when this delete images for family unauthorized response has a 2xx status code
func (o *DeleteImagesForFamilyUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete images for family unauthorized response has a 3xx status code
func (o *DeleteImagesForFamilyUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete images for family unauthorized response has a 4xx status code
func (o *DeleteImagesForFamilyUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete images for family unauthorized response has a 5xx status code
func (o *DeleteImagesForFamilyUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete images for family unauthorized response a status code equal to that given
func (o *DeleteImagesForFamilyUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete images for family unauthorized response
func (o *DeleteImagesForFamilyUnauthorized) Code() int {
	return 401
}

func (o *DeleteImagesForFamilyUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteImagesForFamilyUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteImagesForFamilyUnauthorized) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImagesForFamilyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImagesForFamilyInternalServerError creates a DeleteImagesForFamilyInternalServerError with default headers values
func NewDeleteImagesForFamilyInternalServerError() *DeleteImagesForFamilyInternalServerError {
	return &DeleteImagesForFamilyInternalServerError{}
}

/*
DeleteImagesForFamilyInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteImagesForFamilyInternalServerError struct {
	Payload *workload_models.StackpathapiStatus
}

// IsSuccess returns true when this delete images for family internal server error response has a 2xx status code
func (o *DeleteImagesForFamilyInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete images for family internal server error response has a 3xx status code
func (o *DeleteImagesForFamilyInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete images for family internal server error response has a 4xx status code
func (o *DeleteImagesForFamilyInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete images for family internal server error response has a 5xx status code
func (o *DeleteImagesForFamilyInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete images for family internal server error response a status code equal to that given
func (o *DeleteImagesForFamilyInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete images for family internal server error response
func (o *DeleteImagesForFamilyInternalServerError) Code() int {
	return 500
}

func (o *DeleteImagesForFamilyInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteImagesForFamilyInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteImagesForFamilyInternalServerError) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImagesForFamilyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImagesForFamilyDefault creates a DeleteImagesForFamilyDefault with default headers values
func NewDeleteImagesForFamilyDefault(code int) *DeleteImagesForFamilyDefault {
	return &DeleteImagesForFamilyDefault{
		_statusCode: code,
	}
}

/*
DeleteImagesForFamilyDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type DeleteImagesForFamilyDefault struct {
	_statusCode int

	Payload *workload_models.StackpathapiStatus
}

// IsSuccess returns true when this delete images for family default response has a 2xx status code
func (o *DeleteImagesForFamilyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete images for family default response has a 3xx status code
func (o *DeleteImagesForFamilyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete images for family default response has a 4xx status code
func (o *DeleteImagesForFamilyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete images for family default response has a 5xx status code
func (o *DeleteImagesForFamilyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete images for family default response a status code equal to that given
func (o *DeleteImagesForFamilyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete images for family default response
func (o *DeleteImagesForFamilyDefault) Code() int {
	return o._statusCode
}

func (o *DeleteImagesForFamilyDefault) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] DeleteImagesForFamily default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteImagesForFamilyDefault) String() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] DeleteImagesForFamily default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteImagesForFamilyDefault) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImagesForFamilyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
