// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetImageParams creates a new GetImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImageParams() *GetImageParams {
	return &GetImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageParamsWithTimeout creates a new GetImageParams object
// with the ability to set a timeout on a request.
func NewGetImageParamsWithTimeout(timeout time.Duration) *GetImageParams {
	return &GetImageParams{
		timeout: timeout,
	}
}

// NewGetImageParamsWithContext creates a new GetImageParams object
// with the ability to set a context for a request.
func NewGetImageParamsWithContext(ctx context.Context) *GetImageParams {
	return &GetImageParams{
		Context: ctx,
	}
}

// NewGetImageParamsWithHTTPClient creates a new GetImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImageParamsWithHTTPClient(client *http.Client) *GetImageParams {
	return &GetImageParams{
		HTTPClient: client,
	}
}

/*
GetImageParams contains all the parameters to send to the API endpoint

	for the get image operation.

	Typically these are written to a http.Request.
*/
type GetImageParams struct {

	/* ImageFamily.

	   The family of the image to retrieve
	*/
	ImageFamily string

	/* ImageTag.

	     The specific tag of image to retrieve

	This must be present, but can be 'default' to get the default image for the family.
	*/
	ImageTag string

	/* StackID.

	   The ID or slug of the stack containing the image to retrieve
	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageParams) WithDefaults() *GetImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get image params
func (o *GetImageParams) WithTimeout(timeout time.Duration) *GetImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image params
func (o *GetImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image params
func (o *GetImageParams) WithContext(ctx context.Context) *GetImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image params
func (o *GetImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image params
func (o *GetImageParams) WithHTTPClient(client *http.Client) *GetImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image params
func (o *GetImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageFamily adds the imageFamily to the get image params
func (o *GetImageParams) WithImageFamily(imageFamily string) *GetImageParams {
	o.SetImageFamily(imageFamily)
	return o
}

// SetImageFamily adds the imageFamily to the get image params
func (o *GetImageParams) SetImageFamily(imageFamily string) {
	o.ImageFamily = imageFamily
}

// WithImageTag adds the imageTag to the get image params
func (o *GetImageParams) WithImageTag(imageTag string) *GetImageParams {
	o.SetImageTag(imageTag)
	return o
}

// SetImageTag adds the imageTag to the get image params
func (o *GetImageParams) SetImageTag(imageTag string) {
	o.ImageTag = imageTag
}

// WithStackID adds the stackID to the get image params
func (o *GetImageParams) WithStackID(stackID string) *GetImageParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get image params
func (o *GetImageParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param image_family
	if err := r.SetPathParam("image_family", o.ImageFamily); err != nil {
		return err
	}

	// path param image_tag
	if err := r.SetPathParam("image_tag", o.ImageTag); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
