// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/stackpath/virtual-kubelet-stackpath/internal/api/workload/workload_models"
)

// NewUpdateImageDeprecationParams creates a new UpdateImageDeprecationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateImageDeprecationParams() *UpdateImageDeprecationParams {
	return &UpdateImageDeprecationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateImageDeprecationParamsWithTimeout creates a new UpdateImageDeprecationParams object
// with the ability to set a timeout on a request.
func NewUpdateImageDeprecationParamsWithTimeout(timeout time.Duration) *UpdateImageDeprecationParams {
	return &UpdateImageDeprecationParams{
		timeout: timeout,
	}
}

// NewUpdateImageDeprecationParamsWithContext creates a new UpdateImageDeprecationParams object
// with the ability to set a context for a request.
func NewUpdateImageDeprecationParamsWithContext(ctx context.Context) *UpdateImageDeprecationParams {
	return &UpdateImageDeprecationParams{
		Context: ctx,
	}
}

// NewUpdateImageDeprecationParamsWithHTTPClient creates a new UpdateImageDeprecationParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateImageDeprecationParamsWithHTTPClient(client *http.Client) *UpdateImageDeprecationParams {
	return &UpdateImageDeprecationParams{
		HTTPClient: client,
	}
}

/*
UpdateImageDeprecationParams contains all the parameters to send to the API endpoint

	for the update image deprecation operation.

	Typically these are written to a http.Request.
*/
type UpdateImageDeprecationParams struct {

	// Body.
	Body *workload_models.V1ImageDeprecation

	/* ImageFamily.

	   The family of the image to update deprecation for
	*/
	ImageFamily string

	/* ImageTag.

	   The specific tag of image to update deprecation for
	*/
	ImageTag string

	/* StackID.

	   The ID or slug of the stack containing the image to update deprecation for
	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update image deprecation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateImageDeprecationParams) WithDefaults() *UpdateImageDeprecationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update image deprecation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateImageDeprecationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update image deprecation params
func (o *UpdateImageDeprecationParams) WithTimeout(timeout time.Duration) *UpdateImageDeprecationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update image deprecation params
func (o *UpdateImageDeprecationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update image deprecation params
func (o *UpdateImageDeprecationParams) WithContext(ctx context.Context) *UpdateImageDeprecationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update image deprecation params
func (o *UpdateImageDeprecationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update image deprecation params
func (o *UpdateImageDeprecationParams) WithHTTPClient(client *http.Client) *UpdateImageDeprecationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update image deprecation params
func (o *UpdateImageDeprecationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update image deprecation params
func (o *UpdateImageDeprecationParams) WithBody(body *workload_models.V1ImageDeprecation) *UpdateImageDeprecationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update image deprecation params
func (o *UpdateImageDeprecationParams) SetBody(body *workload_models.V1ImageDeprecation) {
	o.Body = body
}

// WithImageFamily adds the imageFamily to the update image deprecation params
func (o *UpdateImageDeprecationParams) WithImageFamily(imageFamily string) *UpdateImageDeprecationParams {
	o.SetImageFamily(imageFamily)
	return o
}

// SetImageFamily adds the imageFamily to the update image deprecation params
func (o *UpdateImageDeprecationParams) SetImageFamily(imageFamily string) {
	o.ImageFamily = imageFamily
}

// WithImageTag adds the imageTag to the update image deprecation params
func (o *UpdateImageDeprecationParams) WithImageTag(imageTag string) *UpdateImageDeprecationParams {
	o.SetImageTag(imageTag)
	return o
}

// SetImageTag adds the imageTag to the update image deprecation params
func (o *UpdateImageDeprecationParams) SetImageTag(imageTag string) {
	o.ImageTag = imageTag
}

// WithStackID adds the stackID to the update image deprecation params
func (o *UpdateImageDeprecationParams) WithStackID(stackID string) *UpdateImageDeprecationParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the update image deprecation params
func (o *UpdateImageDeprecationParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateImageDeprecationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param image_family
	if err := r.SetPathParam("image_family", o.ImageFamily); err != nil {
		return err
	}

	// path param image_tag
	if err := r.SetPathParam("image_tag", o.ImageTag); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
