// Code generated by go-swagger; DO NOT EDIT.

package workload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new workload API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for workload API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	WatchNetworks2(params *WatchNetworks2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*WatchNetworks2OK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
WatchNetworks2 watch networks2 API
*/
func (a *Client) WatchNetworks2(params *WatchNetworks2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*WatchNetworks2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWatchNetworks2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "WatchNetworks2",
		Method:             "GET",
		PathPattern:        "/workload/v1/stacks/{stack_id}/watch/networks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WatchNetworks2Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WatchNetworks2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*WatchNetworks2Default)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
