// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkloadInstanceParams creates a new GetWorkloadInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWorkloadInstanceParams() *GetWorkloadInstanceParams {
	return &GetWorkloadInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkloadInstanceParamsWithTimeout creates a new GetWorkloadInstanceParams object
// with the ability to set a timeout on a request.
func NewGetWorkloadInstanceParamsWithTimeout(timeout time.Duration) *GetWorkloadInstanceParams {
	return &GetWorkloadInstanceParams{
		timeout: timeout,
	}
}

// NewGetWorkloadInstanceParamsWithContext creates a new GetWorkloadInstanceParams object
// with the ability to set a context for a request.
func NewGetWorkloadInstanceParamsWithContext(ctx context.Context) *GetWorkloadInstanceParams {
	return &GetWorkloadInstanceParams{
		Context: ctx,
	}
}

// NewGetWorkloadInstanceParamsWithHTTPClient creates a new GetWorkloadInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWorkloadInstanceParamsWithHTTPClient(client *http.Client) *GetWorkloadInstanceParams {
	return &GetWorkloadInstanceParams{
		HTTPClient: client,
	}
}

/*
GetWorkloadInstanceParams contains all the parameters to send to the API endpoint

	for the get workload instance operation.

	Typically these are written to a http.Request.
*/
type GetWorkloadInstanceParams struct {

	/* InstanceName.

	   The name of the instance to retrieve
	*/
	InstanceName string

	/* StackID.

	   The ID of the stack containing the workload whose instance to retrieve
	*/
	StackID string

	/* WorkloadID.

	   The ID of the workload whose instance to retrieve
	*/
	WorkloadID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get workload instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkloadInstanceParams) WithDefaults() *GetWorkloadInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get workload instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkloadInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get workload instance params
func (o *GetWorkloadInstanceParams) WithTimeout(timeout time.Duration) *GetWorkloadInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workload instance params
func (o *GetWorkloadInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workload instance params
func (o *GetWorkloadInstanceParams) WithContext(ctx context.Context) *GetWorkloadInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workload instance params
func (o *GetWorkloadInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workload instance params
func (o *GetWorkloadInstanceParams) WithHTTPClient(client *http.Client) *GetWorkloadInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workload instance params
func (o *GetWorkloadInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceName adds the instanceName to the get workload instance params
func (o *GetWorkloadInstanceParams) WithInstanceName(instanceName string) *GetWorkloadInstanceParams {
	o.SetInstanceName(instanceName)
	return o
}

// SetInstanceName adds the instanceName to the get workload instance params
func (o *GetWorkloadInstanceParams) SetInstanceName(instanceName string) {
	o.InstanceName = instanceName
}

// WithStackID adds the stackID to the get workload instance params
func (o *GetWorkloadInstanceParams) WithStackID(stackID string) *GetWorkloadInstanceParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get workload instance params
func (o *GetWorkloadInstanceParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WithWorkloadID adds the workloadID to the get workload instance params
func (o *GetWorkloadInstanceParams) WithWorkloadID(workloadID string) *GetWorkloadInstanceParams {
	o.SetWorkloadID(workloadID)
	return o
}

// SetWorkloadID adds the workloadId to the get workload instance params
func (o *GetWorkloadInstanceParams) SetWorkloadID(workloadID string) {
	o.WorkloadID = workloadID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkloadInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instance_name
	if err := r.SetPathParam("instance_name", o.InstanceName); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	// path param workload_id
	if err := r.SetPathParam("workload_id", o.WorkloadID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
