// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContainerStatusWaiting Properties related to containers that are starting up
//
// swagger:model ContainerStatusWaiting
type ContainerStatusWaiting struct {

	// A more detailed explanation of a container's waiting state
	Message string `json:"message,omitempty"`

	// The reason that a container is waiting to start
	Reason string `json:"reason,omitempty"`
}

// Validate validates this container status waiting
func (m *ContainerStatusWaiting) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this container status waiting based on context it is used
func (m *ContainerStatusWaiting) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerStatusWaiting) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerStatusWaiting) UnmarshalBinary(b []byte) error {
	var res ContainerStatusWaiting
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
