// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateImageRequest A request to create an image
//
// swagger:model v1CreateImageRequest
type V1CreateImageRequest struct {

	// image
	Image *V1Image `json:"image,omitempty"`

	// instance volume source
	InstanceVolumeSource *V1ImageSourceInstanceVolume `json:"instanceVolumeSource,omitempty"`
}

// Validate validates this v1 create image request
func (m *V1CreateImageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstanceVolumeSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateImageRequest) validateImage(formats strfmt.Registry) error {
	if swag.IsZero(m.Image) { // not required
		return nil
	}

	if m.Image != nil {
		if err := m.Image.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("image")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("image")
			}
			return err
		}
	}

	return nil
}

func (m *V1CreateImageRequest) validateInstanceVolumeSource(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceVolumeSource) { // not required
		return nil
	}

	if m.InstanceVolumeSource != nil {
		if err := m.InstanceVolumeSource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instanceVolumeSource")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instanceVolumeSource")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 create image request based on the context it is used
func (m *V1CreateImageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstanceVolumeSource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateImageRequest) contextValidateImage(ctx context.Context, formats strfmt.Registry) error {

	if m.Image != nil {
		if err := m.Image.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("image")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("image")
			}
			return err
		}
	}

	return nil
}

func (m *V1CreateImageRequest) contextValidateInstanceVolumeSource(ctx context.Context, formats strfmt.Registry) error {

	if m.InstanceVolumeSource != nil {
		if err := m.InstanceVolumeSource.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instanceVolumeSource")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instanceVolumeSource")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateImageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateImageRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateImageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
