// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1DockerRegistryCredentials The authentication configuration that should be used to pull images from a docker registry
//
// swagger:model v1DockerRegistryCredentials
type V1DockerRegistryCredentials struct {

	// The email address to use for the docker registry account
	Email string `json:"email,omitempty"`

	// The password that should be used to authenticate the image pull
	Password string `json:"password,omitempty"`

	// The server that the credentials should be used with
	//
	// The server that the credentials should be used with. This value will default to the docker hub registry when not set.
	Server string `json:"server,omitempty"`

	// The username that should be used for authenticate the image pull
	Username string `json:"username,omitempty"`
}

// Validate validates this v1 docker registry credentials
func (m *V1DockerRegistryCredentials) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 docker registry credentials based on context it is used
func (m *V1DockerRegistryCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DockerRegistryCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DockerRegistryCredentials) UnmarshalBinary(b []byte) error {
	var res V1DockerRegistryCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
