// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1EnvironmentVariable The location to obtain a value for an environment variable
//
// swagger:model v1EnvironmentVariable
type V1EnvironmentVariable struct {

	// A sensitive environment variable that should not be exposed
	SecretValue string `json:"secretValue,omitempty"`

	// An environment variable's value
	Value string `json:"value,omitempty"`
}

// Validate validates this v1 environment variable
func (m *V1EnvironmentVariable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 environment variable based on context it is used
func (m *V1EnvironmentVariable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1EnvironmentVariable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1EnvironmentVariable) UnmarshalBinary(b []byte) error {
	var res V1EnvironmentVariable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
