// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1EnvironmentVariableSource The source for an environment variable
//
// swagger:model v1EnvironmentVariableSource
type V1EnvironmentVariableSource struct {

	// instance field ref
	InstanceFieldRef *V1InstanceFieldRef `json:"instanceFieldRef,omitempty"`
}

// Validate validates this v1 environment variable source
func (m *V1EnvironmentVariableSource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInstanceFieldRef(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1EnvironmentVariableSource) validateInstanceFieldRef(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceFieldRef) { // not required
		return nil
	}

	if m.InstanceFieldRef != nil {
		if err := m.InstanceFieldRef.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instanceFieldRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instanceFieldRef")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 environment variable source based on the context it is used
func (m *V1EnvironmentVariableSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInstanceFieldRef(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1EnvironmentVariableSource) contextValidateInstanceFieldRef(ctx context.Context, formats strfmt.Registry) error {

	if m.InstanceFieldRef != nil {
		if err := m.InstanceFieldRef.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instanceFieldRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instanceFieldRef")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1EnvironmentVariableSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1EnvironmentVariableSource) UnmarshalBinary(b []byte) error {
	var res V1EnvironmentVariableSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
