// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1HostAlias The hosts and IPs that will be injected into the container workload instance's hosts file
//
// swagger:model v1HostAlias
type V1HostAlias struct {

	// A list of hostnames to be injected in container workload instance's host file
	Hostnames []string `json:"hostnames"`

	// An IP address to be injected in container workload instance's host file
	IP string `json:"ip,omitempty"`
}

// Validate validates this v1 host alias
func (m *V1HostAlias) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 host alias based on context it is used
func (m *V1HostAlias) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1HostAlias) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1HostAlias) UnmarshalBinary(b []byte) error {
	var res V1HostAlias
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
