// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1MetricSpec v1 metric spec
//
// swagger:model v1MetricSpec
type V1MetricSpec struct {

	// The target average value for the metric measured across all instances within a deployment, expressed as a percentage of requested resources.
	AverageUtilization int32 `json:"averageUtilization,omitempty"`

	// The target average value for the metric measured across all instances within a deployment, expressed as a quantity.
	AverageValue string `json:"averageValue,omitempty"`

	// The metric to measure against
	Metric string `json:"metric,omitempty"`
}

// Validate validates this v1 metric spec
func (m *V1MetricSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 metric spec based on context it is used
func (m *V1MetricSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1MetricSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1MetricSpec) UnmarshalBinary(b []byte) error {
	var res V1MetricSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
