// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1MatchExpression An expression to match selectors against a set of values
//
// swagger:model v1MatchExpression
type V1MatchExpression struct {

	// The name of the selector to perform a match against
	Key string `json:"key,omitempty"`

	// The operation to perform to match a selector
	//
	// Valid values are "In", "NotIn", "Exists", and "DoesNotExist".
	Operator string `json:"operator,omitempty"`

	// The values to match in the selector
	Values []string `json:"values"`
}

// Validate validates this v1 match expression
func (m *V1MatchExpression) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 match expression based on context it is used
func (m *V1MatchExpression) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1MatchExpression) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1MatchExpression) UnmarshalBinary(b []byte) error {
	var res V1MatchExpression
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
