// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TCPSocketAction Connect to an instance's TCP port
//
// swagger:model v1TCPSocketAction
type V1TCPSocketAction struct {

	// The TCP port to quert
	Port int32 `json:"port,omitempty"`
}

// Validate validates this v1 TCP socket action
func (m *V1TCPSocketAction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 TCP socket action based on context it is used
func (m *V1TCPSocketAction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TCPSocketAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TCPSocketAction) UnmarshalBinary(b []byte) error {
	var res V1TCPSocketAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
