// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Workloadv1Instance An instance of a workload deployment
//
// swagger:model workloadv1Instance
type Workloadv1Instance struct {

	// Status of the containers running within the workload instance
	ContainerStatuses []*V1ContainerStatus `json:"containerStatuses"`

	// containers
	Containers V1ContainerSpecMapEntry `json:"containers,omitempty"`

	// The date an instance was created
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"createdAt,omitempty"`

	// The date an instance was deleted
	// Format: date-time
	DeletedAt strfmt.DateTime `json:"deletedAt,omitempty"`

	// An instance's publicly accessible IPv4 address
	ExternalIPAddress string `json:"externalIpAddress,omitempty"`

	// An instance's publicly accessible IPv6 address
	ExternalIPV6Address string `json:"externalIpv6Address,omitempty"`

	// An instance's unique identifier
	ID string `json:"id,omitempty"`

	// Status of the init_containers running within the workload instance
	InitContainerStatuses []*V1ContainerStatus `json:"initContainerStatuses"`

	// init containers
	InitContainers V1ContainerSpecMapEntry `json:"initContainers,omitempty"`

	// An instance's IPv4 address
	IPAddress string `json:"ipAddress,omitempty"`

	// An instance's IPv6 address
	IPV6Address string `json:"ipv6Address,omitempty"`

	// location
	Location *Workloadv1Location `json:"location,omitempty"`

	// A longer message that provides more detail on why an instance is in a phase
	Message string `json:"message,omitempty"`

	// metadata
	Metadata *V1Metadata `json:"metadata,omitempty"`

	// An instance's name
	//
	// Instance names are generated from their corresponsing workload's slug, followed by a unique hash
	Name string `json:"name,omitempty"`

	// An instance's network interfaces
	NetworkInterfaces []*Workloadv1NetworkInterfaceStatus `json:"networkInterfaces"`

	// phase
	Phase *Workloadv1InstanceInstancePhase `json:"phase,omitempty"`

	// A short reason that explains why an instance is in a phase
	Reason string `json:"reason,omitempty"`

	// resources
	Resources *V1ResourceRequirements `json:"resources,omitempty"`

	// runtime
	Runtime *V1WorkloadInstanceRuntimeSettings `json:"runtime,omitempty"`

	// The date an instance was scheduled
	// Format: date-time
	ScheduledAt strfmt.DateTime `json:"scheduledAt,omitempty"`

	// The ID of the stack that an instance belongs to
	StackID string `json:"stackId,omitempty"`

	// The date an instance was started
	// Format: date-time
	StartedAt strfmt.DateTime `json:"startedAt,omitempty"`

	// The status of the virtual machines running within the workload instance
	VirtualMachineStatuses []*V1VirtualMachineStatus `json:"virtualMachineStatuses"`

	// virtual machines
	VirtualMachines V1VirtualMachineSpecMapEntry `json:"virtualMachines,omitempty"`

	// The ID of the workload that an instance belongs to
	WorkloadID string `json:"workloadId,omitempty"`
}

// Validate validates this workloadv1 instance
func (m *Workloadv1Instance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContainerStatuses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContainers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInitContainerStatuses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInitContainers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkInterfaces(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhase(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRuntime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScheduledAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVirtualMachineStatuses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVirtualMachines(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Workloadv1Instance) validateContainerStatuses(formats strfmt.Registry) error {
	if swag.IsZero(m.ContainerStatuses) { // not required
		return nil
	}

	for i := 0; i < len(m.ContainerStatuses); i++ {
		if swag.IsZero(m.ContainerStatuses[i]) { // not required
			continue
		}

		if m.ContainerStatuses[i] != nil {
			if err := m.ContainerStatuses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("containerStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("containerStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) validateContainers(formats strfmt.Registry) error {
	if swag.IsZero(m.Containers) { // not required
		return nil
	}

	if m.Containers != nil {
		if err := m.Containers.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("containers")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("containers")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("createdAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Workloadv1Instance) validateDeletedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.DeletedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deletedAt", "body", "date-time", m.DeletedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Workloadv1Instance) validateInitContainerStatuses(formats strfmt.Registry) error {
	if swag.IsZero(m.InitContainerStatuses) { // not required
		return nil
	}

	for i := 0; i < len(m.InitContainerStatuses); i++ {
		if swag.IsZero(m.InitContainerStatuses[i]) { // not required
			continue
		}

		if m.InitContainerStatuses[i] != nil {
			if err := m.InitContainerStatuses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("initContainerStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("initContainerStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) validateInitContainers(formats strfmt.Registry) error {
	if swag.IsZero(m.InitContainers) { // not required
		return nil
	}

	if m.InitContainers != nil {
		if err := m.InitContainers.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("initContainers")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("initContainers")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) validateLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.Location) { // not required
		return nil
	}

	if m.Location != nil {
		if err := m.Location.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) validateNetworkInterfaces(formats strfmt.Registry) error {
	if swag.IsZero(m.NetworkInterfaces) { // not required
		return nil
	}

	for i := 0; i < len(m.NetworkInterfaces); i++ {
		if swag.IsZero(m.NetworkInterfaces[i]) { // not required
			continue
		}

		if m.NetworkInterfaces[i] != nil {
			if err := m.NetworkInterfaces[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networkInterfaces" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networkInterfaces" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) validatePhase(formats strfmt.Registry) error {
	if swag.IsZero(m.Phase) { // not required
		return nil
	}

	if m.Phase != nil {
		if err := m.Phase.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("phase")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("phase")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) validateResources(formats strfmt.Registry) error {
	if swag.IsZero(m.Resources) { // not required
		return nil
	}

	if m.Resources != nil {
		if err := m.Resources.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) validateRuntime(formats strfmt.Registry) error {
	if swag.IsZero(m.Runtime) { // not required
		return nil
	}

	if m.Runtime != nil {
		if err := m.Runtime.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("runtime")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("runtime")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) validateScheduledAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ScheduledAt) { // not required
		return nil
	}

	if err := validate.FormatOf("scheduledAt", "body", "date-time", m.ScheduledAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Workloadv1Instance) validateStartedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.StartedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("startedAt", "body", "date-time", m.StartedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Workloadv1Instance) validateVirtualMachineStatuses(formats strfmt.Registry) error {
	if swag.IsZero(m.VirtualMachineStatuses) { // not required
		return nil
	}

	for i := 0; i < len(m.VirtualMachineStatuses); i++ {
		if swag.IsZero(m.VirtualMachineStatuses[i]) { // not required
			continue
		}

		if m.VirtualMachineStatuses[i] != nil {
			if err := m.VirtualMachineStatuses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("virtualMachineStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("virtualMachineStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) validateVirtualMachines(formats strfmt.Registry) error {
	if swag.IsZero(m.VirtualMachines) { // not required
		return nil
	}

	if m.VirtualMachines != nil {
		if err := m.VirtualMachines.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("virtualMachines")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("virtualMachines")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this workloadv1 instance based on the context it is used
func (m *Workloadv1Instance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateContainerStatuses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateContainers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInitContainerStatuses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInitContainers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLocation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetworkInterfaces(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePhase(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRuntime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVirtualMachineStatuses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVirtualMachines(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Workloadv1Instance) contextValidateContainerStatuses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ContainerStatuses); i++ {

		if m.ContainerStatuses[i] != nil {
			if err := m.ContainerStatuses[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("containerStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("containerStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) contextValidateContainers(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Containers.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("containers")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("containers")
		}
		return err
	}

	return nil
}

func (m *Workloadv1Instance) contextValidateInitContainerStatuses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InitContainerStatuses); i++ {

		if m.InitContainerStatuses[i] != nil {
			if err := m.InitContainerStatuses[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("initContainerStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("initContainerStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) contextValidateInitContainers(ctx context.Context, formats strfmt.Registry) error {

	if err := m.InitContainers.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("initContainers")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("initContainers")
		}
		return err
	}

	return nil
}

func (m *Workloadv1Instance) contextValidateLocation(ctx context.Context, formats strfmt.Registry) error {

	if m.Location != nil {
		if err := m.Location.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {
		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) contextValidateNetworkInterfaces(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.NetworkInterfaces); i++ {

		if m.NetworkInterfaces[i] != nil {
			if err := m.NetworkInterfaces[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networkInterfaces" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networkInterfaces" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) contextValidatePhase(ctx context.Context, formats strfmt.Registry) error {

	if m.Phase != nil {
		if err := m.Phase.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("phase")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("phase")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) contextValidateResources(ctx context.Context, formats strfmt.Registry) error {

	if m.Resources != nil {
		if err := m.Resources.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) contextValidateRuntime(ctx context.Context, formats strfmt.Registry) error {

	if m.Runtime != nil {
		if err := m.Runtime.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("runtime")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("runtime")
			}
			return err
		}
	}

	return nil
}

func (m *Workloadv1Instance) contextValidateVirtualMachineStatuses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.VirtualMachineStatuses); i++ {

		if m.VirtualMachineStatuses[i] != nil {
			if err := m.VirtualMachineStatuses[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("virtualMachineStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("virtualMachineStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workloadv1Instance) contextValidateVirtualMachines(ctx context.Context, formats strfmt.Registry) error {

	if err := m.VirtualMachines.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("virtualMachines")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("virtualMachines")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Workloadv1Instance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Workloadv1Instance) UnmarshalBinary(b []byte) error {
	var res Workloadv1Instance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
