// Code generated by go-swagger; DO NOT EDIT.

package workloads

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/stackpath/vk-stackpath-provider/internal/api/workload/workload_models"
)

// NewCreateWorkloadParams creates a new CreateWorkloadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateWorkloadParams() *CreateWorkloadParams {
	return &CreateWorkloadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateWorkloadParamsWithTimeout creates a new CreateWorkloadParams object
// with the ability to set a timeout on a request.
func NewCreateWorkloadParamsWithTimeout(timeout time.Duration) *CreateWorkloadParams {
	return &CreateWorkloadParams{
		timeout: timeout,
	}
}

// NewCreateWorkloadParamsWithContext creates a new CreateWorkloadParams object
// with the ability to set a context for a request.
func NewCreateWorkloadParamsWithContext(ctx context.Context) *CreateWorkloadParams {
	return &CreateWorkloadParams{
		Context: ctx,
	}
}

// NewCreateWorkloadParamsWithHTTPClient creates a new CreateWorkloadParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateWorkloadParamsWithHTTPClient(client *http.Client) *CreateWorkloadParams {
	return &CreateWorkloadParams{
		HTTPClient: client,
	}
}

/*
CreateWorkloadParams contains all the parameters to send to the API endpoint

	for the create workload operation.

	Typically these are written to a http.Request.
*/
type CreateWorkloadParams struct {

	// Body.
	Body *workload_models.V1CreateWorkloadRequest

	/* StackID.

	   The ID of the stack to create the workload in
	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create workload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWorkloadParams) WithDefaults() *CreateWorkloadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create workload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWorkloadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create workload params
func (o *CreateWorkloadParams) WithTimeout(timeout time.Duration) *CreateWorkloadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create workload params
func (o *CreateWorkloadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create workload params
func (o *CreateWorkloadParams) WithContext(ctx context.Context) *CreateWorkloadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create workload params
func (o *CreateWorkloadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create workload params
func (o *CreateWorkloadParams) WithHTTPClient(client *http.Client) *CreateWorkloadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create workload params
func (o *CreateWorkloadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create workload params
func (o *CreateWorkloadParams) WithBody(body *workload_models.V1CreateWorkloadRequest) *CreateWorkloadParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create workload params
func (o *CreateWorkloadParams) SetBody(body *workload_models.V1CreateWorkloadRequest) {
	o.Body = body
}

// WithStackID adds the stackID to the create workload params
func (o *CreateWorkloadParams) WithStackID(stackID string) *CreateWorkloadParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the create workload params
func (o *CreateWorkloadParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateWorkloadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
