name: Build and push Docker image 

on: 
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          pull: true
          file: docker/Dockerfile
          build-args: |
            VERSION_FLAGS=-ldflags=-X main.buildVersion=${{ github.ref_name }} -X main.buildTime=${{ steps.date.outputs.date }}
          tags: ghcr.io/stackpath/virtual-kubelet-stackpath:${{ github.ref_name }}
          labels: org.opencontainers.image.source=https://github.com/stackpath/virtual-kubelet-stackpath
